### ISSUE TITLE
DNS01 runs in to "context deadline exceeded" (namecheap)

### ISSUE THREAD

**Issue by fuog** [remilapeyre/vault-acme#27]
Hello all,

Thank you at this point for all the efforts so far.

I noticed that when requesting a cert, the `vault write ..` command **occasionally** runs into a "context deadline exceeded". measured I could determine that it always happens after about 60 sec. I can't isolate which component is causing the timeout though.

This problem is even greater if i use a forward_proxy with vault.

My Env
Vault-container version `vault:1.7.2` (and `1.7.3`)
provider `namecheap`
vault-acme version `0.0.7` and `0.0.8`

```bash
❯ time vault write acme/certs/mydomain.net common_name=fooo.mydomain.net
Error writing data to acme/certs/mydomain.net: context deadline exceeded

real	1m0.090s
user	0m0.122s
sys	0m0.038s
```

**Comment by fuog** [comment]
i also learnd, from a GCP Envirnoment, that this can also happen if you block direct DNS queries to 0.0.0.0/0 (Egress) The LEGO-Client tries to query some Internet Servers directly. You wont get any feedback if it took too long or if the DNS-query failed - but you run in to the 60 sec limit.

This update does not resolve the problem because the deadline is 60 sec and some successfull acme process took ~ 50 sec and some other request did fail with the DNS open to the entire Internet.  Therefore we need to control this timeout of 60 sec somehow.

**Comment by gardar** [comment]
Did you figure this out?
I ran into a similar issue: https://github.com/remilapeyre/vault-acme/issues/30 and I'm wondering if setting the 'LEGO_TEST_NAMESERVER' might solve the your issue too.

**Comment by remilapeyre** [comment]
Hi @fuog, thanks for opening this issue! Since a54dd130ebe9b1a8e876c67d82159cc428885ae1 it is now possible to explicitly set the DNS resolver to use by setting the `dns_resolvers` parameter on your account. The other parameter controlling this behavior is `ignore_dns_propagation` that might be needed in some situations. 

Please let me know if setting those two parameters properly fixes your issue, if not I will change the way timeouts are set but as far as I understand it should not be an issue as it should already be using the `max_request_duration` parameter in Vault.

**Comment by fuog** [comment]
looks good now
